### ISSUE TITLE
run.py: error: Parser key "config": File does not exist

### ISSUE THREAD

**Issue by Kid-Young** [yuanenming/mb-str#1]
Thanks for your codes. When I want to run your codes in Windows 10 + NVIDIA 3090 + CUDA11.3, I meet an error, says 
`**run.py: error: Parser key "config": File does not exist**` and then join in an file end of the ".yaml"

**Comment by yuanenming** [comment]
Thanks for your attention. This is an argument parsing error. I have re-organized the config folder, So you should pass the right path `src/configs/yelp/yelp_full.yaml`. I will correct the README file.
