### ISSUE TITLE
How to handle new users and new items

### ISSUE THREAD

**Issue by lich0821** [yuanenming/mb-str#10]
Hello Enming. MBSTR seems unable to handle new users and new items (in test stage with a trained model), right? If yes, could you suggest a way to deal with it? Thanks.

**Comment by yuanenming** [comment]
Yes, the MB-STR framework only utilizes the historical interactions of different users where only item ids are involved in this process. If you are familiar with language models in NLP. The item ids are very similar to token ids.

It even does not use user ids explicitly. In real-world recommendation scenarios. there are rich user features or item features to help us learn better models or initialize reasonable models.

Essentially,  the MB-STR learns the item embeddings and how different items will interact under different types of behaviors in a sequential manner.

To cold start with new users and new items. You can initialize new item embeddings using the item with similar attributes (like category). You can copy some historical interactions for new users from users with similar user profiles.

Cold start is a very important topic in the recommendation system. You can refer to some other materials.

**Comment by lich0821** [comment]
Thank you for your recommendation😊

**Comment by Jenzd** [comment]
Do you have any recommendations on how to adapt the model to handle real-world situations that you mentioned?

For example, is it possible to adapt the model to include user and item context features?
