### ISSUE TITLE
GPU used: True;  TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 53613).

### ISSUE THREAD

**Issue by Kid-Young** [yuanenming/mb-str#2]
Thanks for your codes!  When I run your codes, I choose `gpus: 0` in the file of ".yaml",  the codes run correctly but GPU used: False.  When I choose `gpus: 1` in the file of ".yaml", the codes raise TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 53613).

**Comment by yuanenming** [comment]
Hi, sorry for the late reply.

PytorchLightning updates very fast. See if your pytorchlightning version matches the one in this experiment.

(I think `gpus:0` in your case matches `devices:0`).

**Comment by Kid-Young** [comment]
Thanks for your reply!  My pytorchlighting version is the one in your` requirements.txt`, that is **pytorchlighting = 1.5.3** and **PyTorch = 1.12.1**. And When I choose `gpus: 1` in the files of **".yaml"**  the codes raise TimeoutError but GPU used: True. I can`t see the codes for moving the data and model to GPU in your codes.  When I choose `gpus: 0`, I found my gpu is not working.

**Comment by yuanenming** [comment]
It works on my local environment. Can you paste the full error log? I will try to figure out the problem.

**Comment by Kid-Young** [comment]
fit:
  seed_everything: 42
  trainer:
    logger: true
    checkpoint_callback: null
    enable_checkpointing: true
    callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: Val:NDCG@10
        min_delta: 0.0
        patience: 30
        verbose: false
        mode: max
        strict: true
        check_finite: true
        stopping_threshold: null
        divergence_threshold: null
        check_on_train_epoch_end: null
    default_root_dir: logs/yelp/full
    gradient_clip_val: null
    gradient_clip_algorithm: null
    process_position: 0
    num_nodes: 1
    num_processes: 1
    devices: null
    gpus: 0
    auto_select_gpus: false
    tpu_cores: null
    ipus: null
    log_gpu_memory: null
    progress_bar_refresh_rate: null
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    accumulate_grad_batches: null
    max_epochs: null
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    flush_logs_every_n_steps: null
    log_every_n_steps: 50
    accelerator: ddp
    strategy: null
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    weights_summary: top
    weights_save_path: null
    num_sanity_val_steps: 2
    resume_from_checkpoint: null
    profiler: null
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    reload_dataloaders_every_epoch: false
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    prepare_data_per_node: null
    plugins: null
    amp_backend: native
    amp_level: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    stochastic_weight_avg: false
    terminate_on_nan: null
  model:
    backbone:
      class_path: src.models.BERT
      init_args:
        max_len: 50
        num_items: 22734
        n_layer: 2
        n_head: 2
        n_b: 4
        d_model: 16
        dropout: 0.1
        battn: true
        bpff: true
        brpb: true
    b_head: true
  data:
    dataset_code: yelp
    target_behavior: pos
    multi_behavior: true
    min_uc: 3
    num_items: 22734
    max_len: 50
    mask_prob: 0.2
    num_workers: 4
    val_negative_sampler_code: random
    val_negative_sample_size: 99
    train_batch_size: 128
    val_batch_size: 128
    predict_only_target: false
  ckpt_path: null
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.001
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      weight_decay: 1.0e-06
      amsgrad: false
      foreach: null
      maximize: false
      capturable: false

**Comment by Kid-Young** [comment]
![QWCTO2BHU@IROVUX5D)REDL](https://user-images.githubusercontent.com/56811268/196967892-a7737c5a-4c24-4d44-b2ad-ff71b71422a9.png)
![Z{6CVS098EBVT4$5CMUZ4)C](https://user-images.githubusercontent.com/56811268/196967948-3d126816-2c8e-4618-b612-f1d0d64c0731.png)

**Comment by yuanenming** [comment]
OK, I guess this is because the `ddp` accelerator does not work well in your windows platform, try to use `dp`. And there is no significant difference between ddp and dp when only one GPU is used.

**Comment by Kid-Young** [comment]
Thanks for your solution! The problem is solved, but there is a new problem, and it is a code problem.

**Comment by Kid-Young** [comment]
I found a solution to solve the code problem. Thanks for your codes, reply and help.  You are really a _Big God_!
