### ISSUE TITLE
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated 

### ISSUE THREAD

**Issue by Kid-Young** [yuanenming/mb-str#3]
There is a problem when you run the codes in the Windows environment,  RuntimeError： zero-dimensional tensor (at position 0) cannot be concatenated

> loss = torch.cat([o['loss'] for o in training_step_outputs], 0).mean()
change:
> loss = torch.cat([torch.tensor([o['loss']]) for o in training_step_outputs], 0).mean()

And then it will be run correctly.

**Comment by yuanenming** [comment]
Hi, I am not sure what is causing this error. But this may be due to the reduction in loss per batch. Anyway, `o['loss']` should be a 1-d tensor.

**Comment by Kid-Young** [comment]
Thank you!
