### ISSUE TITLE
Model Graph

### ISSUE THREAD

**Issue by Kid-Young** [yuanenming/mb-str#4]
Hello, Your code is backbone to BERT model?

**Comment by yuanenming** [comment]
Hi, Young, The model backbone is a transformer-based model, where dedicated designs are proposed to deal with multiple types of behaviors. Specifically, the self-attention module is designed to consider transitions between different behaviors, and positional embeddings are also designed to be behavior-aware. Whatsmore, we can give behavior-specific predictions by replacing the naive linear prediction head with a multi-task prediction head. The model performs masked item prediction which is similar to the MLM objective in BERT

For more information, you can refer to our paper.

**Comment by Kid-Young** [comment]
Thank you
