### ISSUE TITLE
How to see the final results?

### ISSUE THREAD

**Issue by Kid-Young** [yuanenming/mb-str#5]
I can't see the final results because the files in logs are _garbled codes_      like this:
![~A`8SR~F57QFYCFLAMKK}8I](https://user-images.githubusercontent.com/56811268/197807349-cd3c692f-f94d-4748-8076-a3a262f565d7.png)

**Comment by Kid-Young** [comment]
I don't know whether the problem of PyTorch-lighting or your codes apart from _logs_

**Comment by yuanenming** [comment]
Hi Young, do you mean the tensorboard logs? You can `pip install tensorboard` and use tensorboard to visualize the results and training process as well as other details.

**Comment by Kid-Young** [comment]
OK. Thanks for your reply!

**Comment by Kid-Young** [comment]
Hi Yuan,  I meet a problem that tensorboard can't show the model graph when I want to see the graph of this model. Like this :
![image](https://user-images.githubusercontent.com/56811268/198922462-11c6b81e-10cf-4a52-a941-7eaafa696056.png)

I cannot solve it.  So could you ask advice to me？

**Comment by yuanenming** [comment]
You can see the scalar panel. the graph panel is used to record the computation graph of your neural network. For architectures as complex as transformers, we don't use it.

**Comment by Kid-Young** [comment]
> You can see the scalar panel. the graph panel is used to record the computation graph of your neural network. For architectures as complex as transformers, we don't use it.

Thanks for your reply and extension
