### ISSUE TITLE
About number of epochs.

### ISSUE THREAD

**Issue by JuweiChan** [yuanenming/mb-str#8]
Hi Yuan, sorry to bother. I wonder how many epochs are needed to train the three datasets in the paper, if you still remember.

**Comment by yuanenming** [comment]
Hi, As you can see in the configuration file, we use `patience` for early-stop.  the training epochs actually depend on the dataset. For example, for the small yelp dataset, you may need to train 100-200 epochs. For very large ijcai datasets. you may need to train 20-40 epochs.
